# Generated by Django 3.0.3 on 2020-08-09 11:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('Description', models.TextField(max_length=10000)),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photodes', models.TextField(blank=True, default='image', max_length=1000)),
                ('photo1', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photo2', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('photo3', models.ImageField(blank=True, default='default.png', upload_to='article_pics')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2020, 8, 9, 11, 53, 30, 706760, tzinfo=utc))),
                ('author', models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor_name', models.CharField(max_length=200)),
                ('comment_text', models.TextField()),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ls.Post')),
            ],
        ),
    ]
