# Generated by Django 3.0.3 on 2020-08-09 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0008_auto_20200809_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(default='Post.id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ls.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 15, 45, 25, 223846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 15, 45, 25, 222851, tzinfo=utc)),
        ),
    ]
