# Generated by Django 3.0.3 on 2020-08-09 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0011_auto_20200809_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 11, 18, 775549, tzinfo=utc)),
        ),
    ]
