# Generated by Django 3.0.3 on 2020-08-09 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0012_auto_20200809_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Description1',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Description2',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Description3',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Title1',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Title2',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Title3',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 13, 57, 629471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.TextField(max_length=3000),
        ),
    ]
