# Generated by Django 3.0.3 on 2020-08-09 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0013_auto_20200809_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 23, 39, 829457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description1',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description2',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description3',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
