# Generated by Django 3.0.3 on 2020-08-09 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0014_auto_20200809_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 17, 28, 54, 865365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.TextField(max_length=5000),
        ),
    ]
