# Generated by Django 3.0.3 on 2020-08-09 19:28

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0016_auto_20200809_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 19, 28, 39, 346598, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
