# Generated by Django 3.0.3 on 2020-08-09 19:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0017_auto_20200810_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Description1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Description2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Description3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Title1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Title2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Title3',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
