# Generated by Django 3.0.3 on 2020-08-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ls', '0020_auto_20200810_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcomment',
            name='Post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techcomments', to='ls.TechPost'),
        ),
    ]
